### ISSUE TITLE
请问有没有蓝牙相关的例子？

### ISSUE THREAD

**Issue by saqing** [zepp-health/zeppos-samples#1]
我安装了模拟器，模拟中显示蓝牙连接状态是 true,  我没有连接蓝牙呀,模拟中如何断开蓝牙连接和通过蓝牙发送数据？ 还有就是，设备应用能和我自己开发的手机app进行蓝牙连接吗？有没有文档可以参考？

**Comment by mrcoon** [comment]
蓝牙连接可参考 [TodoList](https://github.com/zepp-health/zeppos-samples/tree/main/application/todo-list) 项目，在模拟器中手机模拟器与手表模拟器通过网络模拟蓝牙通信，模拟器暂未提供断开蓝牙的功能，可以通过mock或真机的方式去验证该场景。
关于三方应用连接手表设备，可以通过接入我们的标准SDK连接手表，详细接入流程可参考[标准SDK](https://dev.zepp.com/#/home/docs/remote?page=sdk-about)，如果需要单独与设备里某个应用通信，目前暂未开放这方面的能力
