### ISSUE TITLE
Is it possible to get SN code, Bluetooth physical address or other unique device identification number? 

### ISSUE THREAD

**Issue by AntoniotheFuture** [zepp-health/zeppos-samples#10]
I want to create some device-identification Apps in zepp OS. But none found in https://docs.zepp.com/docs/intro/

**Comment by mrcoon** [comment]
This information is not available at this time, please refer to the following document for basic device information: https://docs.zepp.com/zh-cn/docs/reference/device-app-api/hmSetting/getDeviceInfo/
