### ISSUE TITLE
Simulator's HotKeys not working

### ISSUE THREAD

**Issue by iron-viper** [zepp-health/zeppos-samples#12]
Hello, I faced with an issue.
OS: Ubuntu 20.04
Home key or fn + ← on keyboard can unlocks the watch simulator - not working.

**Comment by duantengyuan** [comment]
If you have the ”home“ key on your keyboard, you can try pressing it。

**Comment by duantengyuan** [comment]
> 您好，我遇到了一个问题。 操作系统：Ubuntu 20.04 Home 键或键盘上的 fn + ← 可以解锁手表模拟器 - 不工作。

如果您的键盘上有“home”键，您可以尝试按下它。

**Comment by duantengyuan** [comment]
> Hello, I faced with an issue. OS: Ubuntu 20.04 Home key or fn + ← on keyboard can unlocks the watch simulator - not working.

You can also feed back your questions on our feedback platform ”https://zeppcommunity.slack.com/“

**Comment by iron-viper** [comment]
Thx, it's working but I can't see my app in the menu. Also I can't login to [https://zeppcommunity.slack.com/“](https://zeppcommunity.slack.com/%E2%80%9C) because it's saying that 
`Don’t have an @zepp.com email address?
Contact the workspace administrator at Zepp Community for an invitation.`

**Comment by mrcoon** [comment]
> Thx, it's working but I can't see my app in the menu. ![1](https://user-images.githubusercontent.com/1132974/179462085-f68e0944-2e1b-40d1-a8cc-fa3e62053bf9.png) ![2](https://user-images.githubusercontent.com/1132974/179462089-08bb6f99-50e9-491d-a5b1-db7196d8df4c.png)
> 
> Also I can't login to [https://zeppcommunity.slack.com/“](https://zeppcommunity.slack.com/%E2%80%9C) because it's saying that `Don’t have an @zepp.com email address? Contact the workspace administrator at Zepp Community for an invitation.` ![3](https://user-images.githubusercontent.com/1132974/179463373-7f2f6625-c0b5-4b84-a113-2e6878463c73.png)

Click on the app that needs to be installed in the Apps list and you will see it in the watch simulator.

Try to join the slack developers group via the following link: https://t.zepp.com/t/zepp-community-slack

**Comment by iron-viper** [comment]
![image](https://user-images.githubusercontent.com/1132974/179467733-83080bdf-954f-4cef-89c3-f7e76155883e.png)
The same

**Comment by iron-viper** [comment]
@mrcoon @duantengyuan @MyoungXUE Could you please help me to join into Slack community?

**Comment by mrcoon** [comment]
> @mrcoon @duantengyuan @MyoungXUE Could you please help me to join into Slack community?

@iron-viper Sorry, the link provided by my colleague was incorrect. Please use the link I provided, it is possible to join using a personal account.
