### ISSUE TITLE
messageBuilder it does not work

### ISSUE THREAD

**Issue by Ki11Z0n3** [zepp-health/zeppos-samples#13]
Hello, 
I'm testing the application fetch-api and it doesn't work, pressing the button does nothing
```
messageBuilder.request({
       method: "GET_DATA",
 })
```

**Comment by mrcoon** [comment]
@Ki11Z0n3 The appId needs to be the same as the app.json when using MessageBuilder, please check if it is not working due to this reason

**Comment by Ki11Z0n3** [comment]
yes, that was it, thank you very much for the quick response
