### ISSUE TITLE
Amazfit Band 7 support?

### ISSUE THREAD

**Issue by everythingishacked** [zepp-health/zeppos-samples#34]
Is it possible to develop for the Amazfit 7? It's listed as an option with v1 API support, but nothing seems to work.

None of the sample applications list this device as a platform, and even using `zeus create` to generate an app specifically for only Amazfit 7 results in three `gtr3-pro` platforms in the `app.json` config, but not the intended device.

**Comment by isax5** [comment]
Facing the same problem, I really like the band 7 (more than the watches) and I'm lookin the way to target the Amazfit band 7

**Comment by isax5** [comment]
@everythingishacked I found the way to target the Amazfit band 7. 
taking a look to the code of the free apps already available in the App Store in the repository of the developers I found the target they use:

        {
          "name": "ab7",
          "deviceSource": 252
        },
        {
          "name": "ab7-w",
          "deviceSource": 253
        },

So your app.json file shout look a little like this one
<img width="454" alt="Captura de Pantalla 2023-06-20 a la(s) 12 50 14" src="https://github.com/zepp-health/zeppos-samples/assets/17623679/743b7235-2e18-4abf-8e31-591b47ffbabe">


I'm not so sure what the number 254 mean but it comes from here: https://docs.zepp.com/docs/reference/related-resources/device-list/#devices-with-zepp-os


Related to issue #17 
@expected-ingot it may work for you too

**Comment by isax5** [comment]
Correction 1:

Looking at the templates, I could create one for Amazfit ban 7
Steps:
- zeus create new-app
- Select App
- Select OS 1.0 API.....
- Select Empty
- Should this application contain a app-side component? (Y/n): n
- Using space-bar select Amazfit Band 7
- Press Enter


You will see this configuration on the app.json file:

        {
          "name": "amazfit-band7-nfc",
          "deviceSource": 252
        },
        {
          "name": "amazfit-band7",
          "deviceSource": 253
        },
        {
          "name": "amazfit-band7-w",
          "deviceSource": 254
        }


I thing this should be the right configuration to use with the band 7
<img width="575" alt="Captura de Pantalla 2023-06-20 a la(s) 15 11 21" src="https://github.com/zepp-health/zeppos-samples/assets/17623679/5f9de47b-ddf2-4799-aecd-d92bbd6d0f9e">

**Comment by everythingishacked** [comment]
Following those steps and selecting Amazfit Band 7, for some reason my wizard still fills out a config that builds for GTR, which is why I'd questioned support initially:

```
      "platforms": [
        {
          "name": "gtr3-pro",
          "deviceSource": 229
        },
        {
          "name": "gtr3-pro-w",
          "deviceSource": 230
        },
        {
          "name": "gtr3-pro-meilin",
          "deviceSource": 6095106
        }
```

I'll try manually modifying the config to match the Amazfit platforms, but couldn't get anything to successfully build for it before.

Maybe it works with a different (older?) version of `zeus`? Looks like I'm running `1.2.3`

**Comment by isax5** [comment]
> Following those steps and selecting Amazfit Band 7, for some reason my wizard still fills out a config that builds for GTR, which is why I'd questioned support initially:
> 
> ```
>       "platforms": [
>         {
>           "name": "gtr3-pro",
>           "deviceSource": 229
>         },
>         {
>           "name": "gtr3-pro-w",
>           "deviceSource": 230
>         },
>         {
>           "name": "gtr3-pro-meilin",
>           "deviceSource": 6095106
>         }
> ```
> 
> I'll try manually modifying the config to match the Amazfit platforms, but couldn't get anything to successfully build for it before.
> 
> Maybe it works with a different (older?) version of `zeus`? Looks like I'm running `1.2.3`

Yeah, maybe it's your `zeus` version

**Comment by devmdeniz** [comment]
> Correction 1:
> 
> Looking at the templates, I could create one for Amazfit ban 7 Steps:
> 
> * zeus create new-app
> * Select App
> * Select OS 1.0 API.....
> * Select Empty
> * Should this application contain a app-side component? (Y/n): n
> * Using space-bar select Amazfit Band 7
> * Press Enter
> 
> You will see this configuration on the app.json file:
> 
> ```
>     {
>       "name": "amazfit-band7-nfc",
>       "deviceSource": 252
>     },
>     {
>       "name": "amazfit-band7",
>       "deviceSource": 253
>     },
>     {
>       "name": "amazfit-band7-w",
>       "deviceSource": 254
>     }
> ```
> 
> I thing this should be the right configuration to use with the band 7 <img alt="Captura de Pantalla 2023-06-20 a la(s) 15 11 21" width="575" src="https://user-images.githubusercontent.com/17623679/247236969-5f9de47b-ddf2-4799-aecd-d92bbd6d0f9e.png">

Wich zeus version do you use

**Comment by devmdeniz** [comment]
> Is it possible to develop for the Amazfit 7? It's listed as an option with v1 API support, but nothing seems to work.
> 
> None of the sample applications list this device as a platform, and even using `zeus create` to generate an app specifically for only Amazfit 7 results in three `gtr3-pro` platforms in the `app.json` config, but not the intended device.

Did you make it?

**Comment by everythingishacked** [comment]
@devmdeniz thanks for the follow up. I gave up on this project months ago in favor of a chest strap with more accurate HR readings.

**Comment by devmdeniz** [comment]
> @devmdeniz thanks for the follow up. I gave up on this project months ago in favor of a chest strap with more accurate HR readings.

> @devmdeniz thanks for the follow up. I gave up on this project months ago in favor of a chest strap with more accurate HR readings.

If you use the 
```
Zeus init
```
command in CMD and select the ``Empty`` option you can see the ``Band 7`` option.

But I guess that doesn't matter to you anymore.
You can close issue. Have a good day
